upstream:
    default:
      - 1.1.1.1 # cloudflare
      - tcp-tls:cloudflare-dns.com:853
      - https://cloudflare-dns.com/dns-query
      - 8.8.8.8 # google
      - tcp-tls:dns.google:853
      - https://dns.google/dns-query
    
caching:
  minTime: 5m
  maxTime: 1h
  prefetching: true
blocking:
  blackLists:
    ads:
      - https://energized.pro/ultimate/formats/hosts
    special:
      # - https://block.energized.pro/extensions/xtreme/formats/hosts
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/crowed_list.txt
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - http://sysctl.org/cameleon/hosts
      - https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
  whiteLists:
    ads:
      - whitelist.txt
  clientGroupsBlock:
    default:
      - ads
      - special
  blockType: zeroIp
prometheus:
  enable: true
port: 53
httpPort: 4000